Don't exit workflow on failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,13 +16,13 @@ jobs:
       - name: Install dependencies
         run: pnpm install
       - name: check-failing-1 (quoted path with glob at end - fails silently, misses files)
-        run: pnpm run check-failing-1
+        run: pnpm run check-failing-1 || echo 'Failed'
       - name: check-failing-2 (dot slash dir path at start - fails silently, misses files)
-        run: pnpm run check-failing-2
+        run: pnpm run check-failing-2 || echo 'Failed'
       - name: check-failing-3 (glob path at start - fails silently, lints 1st file, misses 2nd file)
-        run: pnpm run check-failing-3
+        run: pnpm run check-failing-3 || echo 'Failed'
       - name: check-failing-4 (dot at start - fails silently, misses files)
-        run: pnpm run check-failing-4
+        run: pnpm run check-failing-4 || echo 'Failed'
       - name: check-working-1 (dot slash file path at start - works, no issues found)
         run: pnpm run check-working-1
       - name: check-working-2 (dot slash path with single wildcard at start - works, no issues found)
